### PR TITLE
fixes replaced external libraries for images with vector images for menus

### PR DESCRIPTION
**Pull request by oers**

### CODE REVIEW

**Comment by Insti** [comment]
I can't see the vector menu images in the built app on the emulator, I expect this is due to some Android Studio caching issue.
What did you do to fix the problem you were having seeing the vector images I addded?

**Comment by Insti** [comment]
Landscape mode seems to work though 👍

**Comment by oers** [comment]
I updated the min sdk to 21 :)

Geoff Hubbard <notifications@github.com> schrieb am Sa., 27. Juli 2019,
18:47:

**Comment by Insti** [comment]
It might be good to add Landscape mode to the release notes document.

**Comment by oers** [comment]
thanks for the feedback the icons disappeared for me too. I will check it out.

**Comment by oers** [comment]
I fixed it on the development branch

**Comment by Insti** [comment]
https://github.com/oers/reversatile/commit/f84e64558f0b312e9a2793200225c22de800d653

Works for me 👍

**Pull request merged**
